/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eval01
import eval01.utils.Cui

class App() {
    fun cuiExample () {
        Cui().example()
    }
}

fun main() {
    App().cuiExample()
}
