/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eval01

import kotlin.test.Test
import kotlin.test.assertNotNull
import eval01.App

class AppTest {
    @Test fun `App does Exist`() {
        val classUnderTest = App()
        assertNotNull(classUnderTest, "app should exist")
    }
}
